=== AustinRoeder/Technical-Exercise/category-system-api/target/classes/schemas/user.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Claims": {
      "type": "array",
      "items": {}
    },
    "Household": {
      "type": "object",
      "properties": {
        "Id": {
          "type": "integer"
        },
        "Name": {
          "type": "string"
        }
      }
    },
    "Logins": {
      "type": "array",
      "items": {}
    },
    "Roles": {
      "type": "array",
      "items": {}
    },
    "FName": {
      "type": "null"
    },
    "LName": {
      "type": "null"
    },
    "DisplayName": {
      "type": "string"
    },
    "HouseholdId": {
      "type": "integer"
    },
    "Email": {
      "type": "string"
    },
    "EmailConfirmed": {
      "type": "boolean"
    },
    "PasswordHash": {
      "type": "string"
    },
    "SecurityStamp": {
      "type": "string"
    },
    "PhoneNumber": {
      "type": "null"
    },
    "PhoneNumberConfirmed": {
      "type": "boolean"
    },
    "TwoFactorEnabled": {
      "type": "boolean"
    },
    "LockoutEndDateUtc": {
      "type": "null"
    },
    "LockoutEnabled": {
      "type": "boolean"
    },
    "AccessFailedCount": {
      "type": "integer"
    },
    "Id": {
      "type": "string"
    },
    "UserName": {
      "type": "string"
    }
  }
}

=== AustinRoeder/Technical-Exercise/category-system-api/src/main/api/examples/user_example.json
{
  "Claims": [],
  "Household": {
    "Id": 12,
    "Name": "Works"
  },
  "Logins": [],
  "Roles": [],
  "FName": null,
  "LName": null,
  "DisplayName": "Austin",
  "HouseholdId": 12,
  "Email": "ausynr@gmail.com",
  "EmailConfirmed": false,
  "PasswordHash": "AAgNoI8t/WwByH4xK8xoOTyqJ/992nVI8IIHdYkQwLfe4sm8XlGf5BhEotSw8OMOdg==",
  "SecurityStamp": "fb7c3132-6af8-40ab-bc82-3bc965b3baff",
  "PhoneNumber": null,
  "PhoneNumberConfirmed": false,
  "TwoFactorEnabled": false,
  "LockoutEndDateUtc": null,
  "LockoutEnabled": false,
  "AccessFailedCount": 0,
  "Id": "84385863-0af0-4c64-8fe1-ae227f7d4351",
  "UserName": "ausynr@gmail.com"
}
